### ISSUE TITLE
PyPI conflict

### ISSUE THREAD

**Issue by jayvdb** [ateliedocodigo/py-queue-manager#20]
setup.py advertises this library as using name `queue-manager`.

However that name is owned by https://pypi.org/project/Queue-Manager/ @ https://gitlab.com/riftool/queue-manager

Would you be able to use another name, and register it on PyPI to avoid future conflicts.

**Comment by luiscoms** [comment]
Hi @jayvdb , thanks for advise, I just upload to pypi https://pypi.org/project/PyQueueManager/
Fixed by #21
