### ISSUE TITLE
pika version

### ISSUE THREAD

**Issue by fmors** [ateliedocodigo/py-queue-manager#3]
Luizito, o **pika** lançou uma major version esta noite (sério) que é incompatível com o py-queue-manager! O erro é devido ao parâmetro `stop_ioloop_on_close`, que não é reconhecido na versão 1.0.0. Recomendo que, por hora, tu coloque no requirements `pika<1.0.0` para garantir... :)

Quando der, vou tentar implementar um fix e te pedir um pull request hehehe.

Abraço!

**Comment by luiscoms** [comment]
Xóia, já estou mexendo

**Comment by luiscoms** [comment]
Released [1.6.0](https://github.com/ateliedocodigo/py-queue-manager/releases/tag/1.6.0) com a correção 😃
